Change group by and moved to graph
hasadna/open-bus-map-search pull request #173
Opened 2023-11-04 20:12 UTC by TomRytt

# Description
1. Moved the group by time/hour to the location of the graph it was manipulating
2. Changed the switch to a button
3. Improved the wording of the button and the title
4. Removed a "-" sign which was left alone in the top menu

## screenshots

Before:
![image](https://github.com/hasadna/open-bus-map-search/assets/86921461/dc385687-7b9c-4b8d-afd0-edc37969b75b)

After:
![image](https://github.com/hasadna/open-bus-map-search/assets/86921461/b47d2788-dfe5-46fd-8b59-a9d0612e0c46)

2023-11-05 03:19 UTC, shootermv commented on src/pages/dashboard/DashboardPage.tsx
Can you please remove the commented out code?
😀

2023-11-05 04:10 UTC, TomRytt commented on src/pages/dashboard/DashboardPage.tsx
Sure, done :)

2023-11-05 04:31 UTC, shootermv commented on src/pages/dashboard/DashboardPage.tsx
Good job!

2023-11-05 04:39 UTC, shootermv commented
Can i ask you- replace button by two buttons
Where only one can be 'on' at the time
That way it will be clear what is the current mode
(I think it called radio buttons)

2023-11-05 07:48 UTC, TomRytt commented
> Can i ask you- replace button by two buttons
> Where only one can be 'on' at the time
> תגוצה רגילה
> תצוגה לפי שעה
> That way it will be clear what is the current mode
> (I think it called radio buttons)
> Like [here](https://codesandbox.io/s/yvwzvm)

That is actually why I updated the title to show the current mode according to the state and then text on the button always shows the opposite. If you think it will still be better then sure, I'll do it this evening.

Also, I think that "תצוגה לפי יום" better reflects what it does than "תצוגה רגילה"

2023-11-05 09:20 UTC, TomRytt commented
> you right, 
> it better to be: 
> לפי שעה & לפי יום
> but i still thinK it is better to have both buttons - so user will see all the possible options...
> ![image](https://github.com/hasadna/open-bus-map-search/assets/1336862/39bdf7a0-fc2c-4eab-a246-04fdc4aa9bd7)
> 

Great, I'll modify it this evening

2023-11-05 09:47 UTC, shootermv commented
you right, 
it better to be: 
לפי שעה & לפי יום
but i still thing it is better to have both buttons - so user will see all the possible options...
![image](https://github.com/hasadna/open-bus-map-search/assets/1336862/39bdf7a0-fc2c-4eab-a246-04fdc4aa9bd7)

2023-11-05 11:25 UTC, NoamGaash approved these changes
lgtm
thanks

2023-11-05 17:32 UTC, TomRytt commented
> you right, it better to be: לפי שעה & לפי יום but i still thinK it is better to have both buttons - so user will see all the possible options... ![image](https://user-images.githubusercontent.com/1336862/280515706-39bdf7a0-fc2c-4eab-a246-04fdc4aa9bd7.png)

Changed to radio group buttons as you requested :)
![image](https://github.com/hasadna/open-bus-map-search/assets/86921461/c246c881-9a84-4334-88d0-3274c5f412f9)

2023-11-05 17:56 UTC, shootermv approved these changes
well done!

2023-11-05 19:12 UTC, shootermv requested changes
need to fix the playwright tests
(matter of changing the expected text)

2023-11-05 20:21 UTC, TomRytt commented
> need to fix the playwright tests (matter of changing the expected text)

Done

2023-11-06 04:27 UTC, shootermv approved these changes

2023-11-06 04:32 UTC, merged

2023-11-06 04:40 UTC, shootermv commented
Thank you for your contribution!
Hope you will continue to work on this project and make more good stuff