#issue 187 lazy load - dynamic import
hasadna/open-bus-map-search pull request #218
Opened 2023-11-14 14:13 UTC by KazemHe

# Description

implemented lazy loading for the pages using daynamic import #issue 187

2023-11-14 22:16 UTC, NoamGaash requested changes
please ask me for review once conflicts are resolved

2023-11-15 11:36 UTC, shootermv approved these changes

2023-11-15 13:35 UTC, NoamGaash requested changes

2023-11-15 13:35 UTC, NoamGaash commented on src/routes/index.tsx
> +import CircularProgress from '@mui/material/CircularProgress'
it won't do the trick.
we want to wait with the loading until the user clicks the menu item - that's not what your code is doing

2023-11-15 15:01 UTC, NoamGaash commented on src/routes/index.tsx
> +import CircularProgress from '@mui/material/CircularProgress'
my bad.
after reading [the documentation](https://react.dev/reference/react/lazy), you're 100% right.
it will solve the issue perfectly.
thanks!

2023-11-15 15:02 UTC, NoamGaash approved these changes

2023-11-15 15:02 UTC, merged