When you click on the logo it goes to the dashboard
hasadna/open-bus-map-search pull request #234
Opened 2023-11-20 15:36 UTC by chaimbinder

# Description
<Please describe the suggested changes>
When you click on the logo it goes to the dashboard #229

2023-11-20 16:10 UTC, shootermv requested changes

2023-11-20 17:07 UTC, giladfuchs commented on src/layout/sidebar/SideBar.tsx
i suggest adding        
i18 instead Hebrew hardcoded

`{t(TEXT_KEYS.website_name)}`

2023-11-21 09:55 UTC, NoamGaash commented
Congrats for your first contribution!
Thanks for joining us.

2023-11-21 09:57 UTC, NoamGaash approved these changes
As I see it, this code can be merged.
Please let us know if you want to make the suggested changes, or let it be merged as-is.
Thanks, and welcome :partying_face: :balloon: 
Noam

2023-11-21 12:27 UTC, NoamGaash commented on src/layout/sidebar/SideBar.tsx
the `TEXT_KEYS` constant should be removed
```js
{t(`website_name`)}
```

2023-11-22 08:55 UTC, shootermv approved these changes

2023-11-22 08:57 UTC, merged