fix: collapsible menu slowness
hasadna/open-bus-map-search pull request #255
Opened 2023-11-28 18:21 UTC by xoRmalka

Update for #254 #215 

# Description
The collapsible menu on the dashboard page was slow when opening and closing

2023-11-28 19:04 UTC, NoamGaash commented
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/00a22799-9920-4b24-811d-a25ed588a277)

2023-11-28 19:07 UTC, NoamGaash requested changes
lets use responsive containers rather than state maintenance

2023-11-28 19:07 UTC, NoamGaash commented on src/pages/dashboard/ArrivalByTimeChart/ArrivalByTimeChart.tsx
> +    maxWidth: containerWidth ? `${containerWidth - 380}px` : '100%',
https://github.com/hasadna/open-bus-map-search/pull/250#discussion_r1406614005

2023-11-29 16:28 UTC, xoRmalka commented
After digging around the web and the documentation 📢 
I found that "ResponsiveContainer" has a "debounce" prop that can be used to control how often the resize event is handled.

@NoamGaash @shootermv

2023-11-29 16:38 UTC, shootermv approved these changes

2023-11-29 18:44 UTC, NoamGaash approved these changes

2023-11-29 18:44 UTC, merged