Create a secret route
hasadna/open-bus-map-search pull request #279
Opened 2023-12-05 09:39 UTC by Haim-S

I added an isProtected key to the array of paths, which checks which path needs protection.

And then, I built in the route tag, a condition that checks if it's protected, then it doesn't go through, and if so, then it goes through.

Hope you liked it, this is my first open source contribution.

2023-12-05 10:09 UTC, ArkadiK94 requested changes
Hi, thanks for your contribution. I have some comments. The main one is to use yarn instead of npm.

2023-12-05 10:09 UTC, ArkadiK94 commented on src/routes/ProtectedRoute.tsx
> +const ProtectedRoute = ({children}:any) => {
Hmm, we don't have authentication on the site so we don't need a Protected Route, the option to get to this page will be through "hidden secret egg" as the storybook.

2023-12-16 00:43 UTC, ArkadiK94 commented
@NoamGaash can we close this pr?

@Haim-S your contribution is very appreciated even though it wasn't as requested because some misunderstanding. You are welcome to take another issue :)

2023-12-16 09:52 UTC, NoamGaash commented
@Haim-S @ArkadiK94 it's inactive for a couple of weeks now, I believe it can be closed.
@Haim-S please let us know if you want to reopen it, maybe there's a misunderstanding from our side,
thank you for participating openbus development efforts

2023-12-16 09:52 UTC, closed without merging

2023-12-17 09:03 UTC, Haim-S commented
Thank you for the opportunity to contribute to your open source, I would
really like to understand where I can contribute and what you would really
like, if there is a meeting on Discord then I would love to join and keep
me updated, thanks.

‫בתאריך שבת, 16 בדצמ׳ 2023 ב-11:52 מאת ‪NoamGaash‬‏ <‪
***@***.***‬‏>:‬

> Closed #279 <https://github.com/hasadna/open-bus-map-search/pull/279>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hasadna/open-bus-map-search/pull/279#event-11265455089>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZBP3DEIHSEO4KHVZZJTPPDYJVVPXAVCNFSM6AAAAABAHLXRFSVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJRGI3DKNBVGUYDQOI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-12-17 09:26 UTC, NoamGaash commented
Hi @Haim-S , thank you!
Feel free to join our [discord](https://discord.com/channels/1089589164707684443/1150649893799608401) channel and [slack](https://join.slack.com/t/hasadna/shared_invite/zt-21qipktl1-7yF4FYJVxAqXl0wE4DlMKQ) channel.
Also, consider making smaller pull requests - so the development cycle will be shorter. You don't have to solve entire issue in a single pull request - any improvement is a great thing.
how about solving this one?
https://github.com/hasadna/open-bus-map-search/issues/80