Implement toggle button that expands the map for mobile devices
hasadna/open-bus-map-search pull request #302
Opened 2023-12-14 20:40 UTC by Roni750

# Description
As described on Issue #252, I've implemented a toggle button that will expand the map, for devices smaller than 430px wide.

## screenshots
!isExpanded:
![image](https://github.com/hasadna/open-bus-map-search/assets/104915367/57ceb1a5-868b-4d4f-8415-1b4bc1d21743)

isExpanded:
![image](https://github.com/hasadna/open-bus-map-search/assets/104915367/72c81152-73d8-41fa-a0f3-d43495db2784)

2023-12-14 21:19 UTC, NoamGaash requested changes
Welcome to the project! Thanks for your contribution, I'm looking forward to merge your PR! :star_struck: 
(don't create another one. this one will be updated once you'll add new commits to your branch)

2023-12-14 21:19 UTC, NoamGaash commented on package-lock.json
Hi roni, we don't use `npm install` here. Use `yarn` instead. Please create another commit in the same branch and delete the package-lock file. thanks!

2023-12-14 21:19 UTC, NoamGaash commented on yarn.lock
please run `git checkout main yarn.lock` to revert this change, and commit it

2023-12-14 21:19 UTC, NoamGaash commented on src/pages/singleLineMap/index.tsx
> +        <ExpandedContainer>
```suggestion
        <ExpandedContainer className={isExpanded ? 'expanded' : 'collapsed'}>
```
will let you use CSS to control the container design

2023-12-14 21:19 UTC, NoamGaash commented on src/pages/singleLineMap/index.tsx
> +  const [isExpanded, setIsExpanded] = useState<Boolean>(false)
```suggestion
  const [isExpanded, setIsExpanded] = useState<Boolean>(false)
  const toggleExpanded = useCallback(()=>setIsExpanded(expanded => !expanded), [])
```
using `toggleExpanded` will let you have the same function reference

2023-12-15 14:41 UTC, Roni750 commented
> Welcome to the project! Thanks for your contribution, I'm looking forward to merge your PR! 🤩 (don't create another one. this one will be updated once you'll add new commits to your branch)

Hey Noam, thank you so much for the guidelines! I'll do as you said and will update here once it's done.

2023-12-17 15:03 UTC, NoamGaash commented on yarn.lock
please revert this change

2023-12-17 21:10 UTC, NoamGaash commented on src/pages/singleLineMap/index.tsx
> +          <ExpandableMap center={position.loc} zoom={8} scrollWheelZoom={true}>
```suggestion
          <ExpandableMap center={position.loc} zoom={8} scrollWheelZoom={true} className={`${isExpanded ? 'expanded' : 'collapsed'}`}>
```

2023-12-18 08:24 UTC, NoamGaash approved these changes
consider removing the `@media screen and (min-width: 430px) {`.
it could look nice on desktop devices as well.

2023-12-18 14:44 UTC, merged