fix: Display missing data, change axis
hasadna/open-bus-map-search pull request #440
Opened 2024-01-26 10:06 UTC by i5x64BIT

- y-axis changed from automatic to 0-100%
- x-axis changed from utc to days
- axis intervals adjusted
- fill gaps: from 00 to last recorded point
- modify sorting to use momentjs functions (otherwise the gaps aren't handled correctly)
<img width="647" alt="Screenshot 2024-01-26 at 12 05 27" src="https://github.com/hasadna/open-bus-map-search/assets/62185136/4a06fc58-23e2-4fea-89fb-001b5febdd5b">

2024-01-27 20:06 UTC, NoamGaash requested changes
I think we should not fill gaps. We should hide the NaN values instead.
Filling gaps with previous data is showing fake data to the user

2024-01-27 20:06 UTC, NoamGaash commented on src/pages/dashboard/ArrivalByTimeChart/ArrivalByTimeChart.tsx
> +      for (let currentId = 0; currentId <= lastId; currentId++) {
please iterate only valid IDs
```
for(let currentId of newData.map(x=>x.id).filter(unique))
```

2024-02-02 14:45 UTC, i5x64BIT commented
It doesn't look too bad in the end, see the changes

2024-02-07 03:38 UTC, i5x64BIT commented
Hey, linting fails on a file I didn't touch.
Should I commit the fixes for it here?

2024-02-07 11:10 UTC, NoamGaash commented
now it should pass.

2024-02-07 18:33 UTC, i5x64BIT commented
I see you requested a a change, we discussed on #402 that leaving the data out of the graph is a valid choice.
<img width="1193" alt="Screenshot 2024-02-07 at 20 33 15" src="https://github.com/hasadna/open-bus-map-search/assets/62185136/81f35d34-7b5c-4751-81c4-49aea96b3786">

2024-02-07 18:38 UTC, NoamGaash commented
The graph seems amazing, but I didn't have the time to go through the logic.
By the way, can it be simplified?
Anyway, I'll get to it later, thanks for your understanding

2024-02-07 18:41 UTC, i5x64BIT commented on src/pages/dashboard/ArrivalByTimeChart/ArrivalByTimeChart.tsx
> +                percent: null,
Percent is set to null, thus doesnt appear on the graph.

2024-02-07 19:18 UTC, i5x64BIT commented
> The graph seems amazing, but I didn't have the time to go through the logic. By the way, can it be simplified? Anyway, I'll get to it later, thanks for your understanding

Yhea sure, I'll try to explain the main points:
The why - add structure to all graphs (static x and y size)
The how - 
  1. For each unique ID
  2. Get it's points into `allPoints` array
  // Start
  4. startHour = allPoints[0].hour;
  5. While startHour !== 00:00 add null points
  // During
  6. Go over allPoints, whenever the delta between 2 points is bigger then 1 hour, add null points

2024-02-07 19:22 UTC, i5x64BIT commented
> > The graph seems amazing, but I didn't have the time to go through the logic. By the way, can it be simplified? Anyway, I'll get to it later, thanks for your understanding
> 
> Yhea sure, I'll try to explain the main points: The why - add structure to all graphs (static x and y size) The how -
> 
> 1. For each unique ID
> 2. Get it's points into `allPoints` array
>    // Start
> 3. startHour = allPoints[0].hour;
> 4. While startHour !== 00:00 add null points
>    // During
> 5. Go over allPoints, whenever the delta between 2 points is bigger then 1 hour, add null points

From my research Recharts seems to print the data as is, it doesn't allow for holes be default.
Data should be parsed before it passes to Recharts, asking chat confirmed it

2024-02-11 15:12 UTC, NoamGaash commented
@i5x64BIT see [the suggested pr](https://github.com/i5x64BIT/open-bus-map-search/pull/2) I made two days ago

2024-02-22 11:26 UTC, i5x64BIT commented
The test that fails is the legend wrapper, I commited the test removal in this pr.
My design does not have a legened and it looks much cleaner in my opinion.
![image](https://github.com/hasadna/open-bus-map-search/assets/62185136/8d9e3c95-c00f-496a-93f5-0fdf5f26563d)

2024-02-22 17:19 UTC, NoamGaash approved these changes
Great!
Thanks for all of your efforts! It looks amazing

2024-02-23 17:14 UTC, merged