feat: make us SEO compatible (#745)
hasadna/open-bus-map-search pull request #790
Opened 2024-06-09 13:26 UTC by EtayZaslavsky

# Description
1. Created sitemap.js script. It creates a sitemap file in public/sitemap.xml dynamically from the url paths in the src/routes/index.tsx file. The urls get a static base_url (https://open-bus-map-search.hasadna.org.il/).
2. Added "node sitemap.js" to the build process in package.json.
3. Added the sitemap url to robots.txt.
4. Added a "/" prefix to one of the urls in src/routes/index.tsx, for the sitemap.xml regex to find it (as all other urls had it).

2024-06-09 13:39 UTC, EtayZaslavsky commented
didn't pass lint test. My mistake for not testing locally. Opening a new PR

2024-06-09 14:11 UTC, NoamGaash commented on public/sitemap.xml
Let's ignore this file on git, it's autogenerated

2024-06-09 14:11 UTC, NoamGaash commented on sitemap.js
did you try existing tools like [this one?](https://www.npmjs.com/package/react-router-sitemap)

2024-06-09 14:11 UTC, NoamGaash commented on src/routes/index.tsx
> +    path: '/report-a-bug',
is it on purpose?

2024-06-09 14:11 UTC, NoamGaash commented on src/routes/index.tsx
> +    path: '/report-a-bug',
nvm I see it is

2024-06-09 17:12 UTC, EtayZaslavsky commented on sitemap.js
thanks! will change to it and update.

2024-06-17 09:04 UTC, supervxn commented
I have some experience in SEO, how can I help?

2024-06-20 19:30 UTC, EtayZaslavsky commented on sitemap.js
checked this one, works only until react 16 (we use 18).
moreover, last commit was 5 years ago, seems like it is not maintained anymore.
I looked for and didn't find another existing tool, but if you find one I can try it as well.

2024-06-20 21:35 UTC, NoamGaash requested changes
Thanks! So let's just ignore the auto-generated sitemap

2024-06-23 06:51 UTC, EtayZaslavsky commented
could it be that these tests failed without connection the code i pushed?

2024-06-23 12:13 UTC, NoamGaash commented on public/sitemap.xml
let's also delete this file

2024-06-23 12:13 UTC, NoamGaash commented
yes, there's an error in production right now

2024-06-25 19:29 UTC, EtayZaslavsky commented
Is there still a problem?

2024-06-26 09:34 UTC, NoamGaash approved these changes

2024-07-19 06:40 UTC, EtayZaslavsky commented
Hi there :)
is there anything new with the problem?

2024-07-20 15:34 UTC, NoamGaash commented
Im not sure, let's try

2025-01-03 20:14 UTC, merged