refactor: improve donation button accessibility
hasadna/open-bus-map-search pull request #952
Opened 2024-11-27 10:44 UTC by chaniBenziman

# Description
Resolving #949 

## screenshots
Now the button looks like this:
![image](https://github.com/user-attachments/assets/1ed296fa-0832-4855-a06d-845cea61920e)

2024-11-27 14:40 UTC, NoamGaash approved these changes
Thank you!

2024-11-27 14:40 UTC, NoamGaash commented on src/pages/DonateModal/DonateModal.tsx
> +                  לתרום לסדנא →
Great, thank you.
Idea for further improvement - i18n can be incorporated here, but it's not mandatory

2024-11-27 20:43 UTC, NoamGaash requested changes
I think I do have two concerns -

1. I believe that the arrow has the wrong direction
2. the lint should be fixed (`npm run lint:fix` - tell me if you need help with it)

have you tested it on dark mode and english mode?
![image](https://github.com/user-attachments/assets/2428fc8e-81b9-4cc1-aaeb-a1a9d132659f)

2024-12-04 16:58 UTC, chaniBenziman commented
how can i fix it?

2025-06-20 15:40 UTC, AvivAbachi commented
@NoamGaash I remake it

![](https://github.com/user-attachments/assets/b2a84037-120a-46df-9acc-8efbc84ca800)

2025-06-20 15:40 UTC, AvivAbachi commented on src/pages/DonateModal/DonateModal.tsx
> +                  לתרום לסדנא →
fix

2025-06-21 11:13 UTC, merged

2026-02-24 10:12 UTC, NoamGaash commented
@all-contributors please add @chaniBenziman for code and planning